#include-once
#include <Direct2DConstants.au3>






;############################################################################################################
;# D2D1_1_Effects
;############################################################################################################
Global Const $sIID_D2D12DAffineTransform = 		"{6aa97485-6354-4cfc-908c-e4a74f62c96c}"
Global Const $sIID_D2D13DPerspectiveTransform = "{c2844d0b-3d86-46e7-85ba-526c9240f3fb}"
Global Const $sIID_D2D13DTransform = 			"{e8467b04-ec61-4b8a-b5de-d4d73debea5a}"
Global Const $sIID_D2D1ArithmeticComposite = 	"{fc151437-049a-4784-a24a-f1c4daf20987}"
Global Const $sIID_D2D1Atlas = 					"{913e2be4-fdcf-4fe2-a5f0-2454f14ff408}"
Global Const $sIID_D2D1BitmapSource = 			"{5fb6c24d-c6dd-4231-9404-50f4d5c3252d}"
Global Const $sIID_D2D1Blend = 					"{81c5b77b-13f8-4cdd-ad20-c890547ac65d}"
Global Const $sIID_D2D1Border = 				"{2a2d49c0-4acf-43c7-8c6a-7c4a27874d27}"
Global Const $sIID_D2D1Brightness = 			"{8cea8d1e-77b0-4986-b3b9-2f0c0eae7887}"
Global Const $sIID_D2D1ColorManagement = 		"{1a28524c-fdd6-4aa4-ae8f-837eb8267b37}"
Global Const $sIID_D2D1ColorMatrix = 			"{921f03d6-641c-47df-852d-b4bb6153ae11}"
Global Const $sIID_D2D1Composite = 				"{48fc9f51-f6ac-48f1-8b58-3b28ac46f76d}"
Global Const $sIID_D2D1ConvolveMatrix = 		"{407f8c08-5533-4331-a341-23cc3877843e}"
Global Const $sIID_D2D1Crop = 					"{e23f7110-0e9a-4324-af47-6a2c0c46f35b}"
Global Const $sIID_D2D1DirectionalBlur = 		"{174319a6-58e9-49b2-bb63-caf2c811a3db}"
Global Const $sIID_D2D1DiscreteTransfer = 		"{90866fcd-488e-454b-af06-e5041b66c36c}"
Global Const $sIID_D2D1DisplacementMap = 		"{edc48364-0417-4111-9450-43845fa9f890}"
Global Const $sIID_D2D1DistantDiffuse = 		"{3e7efd62-a32d-46d4-a83c-5278889ac954}"
Global Const $sIID_D2D1DistantSpecular = 		"{428c1ee5-77b8-4450-8ab5-72219c21abda}"
Global Const $sIID_D2D1DpiCompensation = 		"{6c26c5c7-34e0-46fc-9cfd-e5823706e228}"
Global Const $sIID_D2D1Flood = 					"{61c23c20-ae69-4d8e-94cf-50078df638f2}"
Global Const $sIID_D2D1GammaTransfer = 			"{409444c4-c419-41a0-b0c1-8cd0c0a18e42}"
Global Const $sIID_D2D1GaussianBlur = 			"{1feb6d69-2fe6-4ac9-8c58-1d7f93e7a6a5}"
Global Const $sIID_D2D1Scale = 					"{9daf9369-3846-4d0e-a44e-0c607934a5d7}"
Global Const $sIID_D2D1Histogram = 				"{881db7d0-f7ee-4d4d-a6d2-4697acc66ee8}"
Global Const $sIID_D2D1HueRotation = 			"{0f4458ec-4b32-491b-9e85-bd73f44d3eb6}"
Global Const $sIID_D2D1LinearTransfer = 		"{ad47c8fd-63ef-4acc-9b51-67979c036c06}"
Global Const $sIID_D2D1LuminanceToAlpha = 		"{41251ab7-0beb-46f8-9da7-59e93fcce5de}"
Global Const $sIID_D2D1Morphology = 			"{eae6c40d-626a-4c2d-bfcb-391001abe202}"
Global Const $sIID_D2D1OpacityMetadata = 		"{6c53006a-4450-4199-aa5b-ad1656fece5e}"
Global Const $sIID_D2D1PointDiffuse = 			"{b9e303c3-c08c-4f91-8b7b-38656bc48c20}"
Global Const $sIID_D2D1PointSpecular = 			"{09c3ca26-3ae2-4f09-9ebc-ed3865d53f22}"
Global Const $sIID_D2D1Premultiply = 			"{06eab419-deed-4018-80d2-3e1d471adeb2}"
Global Const $sIID_D2D1Saturation = 			"{5cb2d9cf-327d-459f-a0ce-40c0b2086bf7}"
Global Const $sIID_D2D1Shadow = 				"{c67ea361-1863-4e69-89db-695d3e9a5b6b}"
Global Const $sIID_D2D1SpotDiffuse = 			"{818a1105-7932-44f4-aa86-08ae7b2f2c93}"
Global Const $sIID_D2D1SpotSpecular = 			"{edae421e-7654-4a37-9db8-71acc1beb3c1}"
Global Const $sIID_D2D1TableTransfer = 			"{5bf818c3-5e43-48cb-b631-868396d6a1d4}"
Global Const $sIID_D2D1Tile = 					"{b0784138-3b76-4bc5-b13b-0fa2ad02659f}"
Global Const $sIID_D2D1Turbulence = 			"{cf2bb6ae-889a-4ad7-ba29-a2fd732c9fc9}"
Global Const $sIID_D2D1UnPremultiply = 			"{fb9ac489-ad8d-41ed-9999-bb6347d110f7}"



;# D2D1_BORDER_MODE
Global Const $D2D1_BORDER_MODE_SOFT        = 0
Global Const $D2D1_BORDER_MODE_HARD        = 1
Global Const $D2D1_BORDER_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_CHANNEL_SELECTOR
Global Const $D2D1_CHANNEL_SELECTOR_R           = 0
Global Const $D2D1_CHANNEL_SELECTOR_G           = 1
Global Const $D2D1_CHANNEL_SELECTOR_B           = 2
Global Const $D2D1_CHANNEL_SELECTOR_A           = 3
Global Const $D2D1_CHANNEL_SELECTOR_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_BITMAPSOURCE_ORIENTATION
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_DEFAULT                             = 1
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_FLIP_HORIZONTAL                     = 2
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE180                 = 3
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE180_FLIP_HORIZONTAL = 4
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE270_FLIP_HORIZONTAL = 5
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE90                  = 6
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE90_FLIP_HORIZONTAL  = 7
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE270                 = 8
Global Const $D2D1_BITMAPSOURCE_ORIENTATION_FORCE_DWORD                         = 0xFFFFFFFF

;# D2D1_GAUSSIANBLUR_PROP
Global Const $D2D1_GAUSSIANBLUR_PROP_STANDARD_DEVIATION = 0
Global Const $D2D1_GAUSSIANBLUR_PROP_OPTIMIZATION       = 1
Global Const $D2D1_GAUSSIANBLUR_PROP_BORDER_MODE        = 2
Global Const $D2D1_GAUSSIANBLUR_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_GAUSSIANBLUR_OPTIMIZATION
Global Const $D2D1_GAUSSIANBLUR_OPTIMIZATION_SPEED       = 0
Global Const $D2D1_GAUSSIANBLUR_OPTIMIZATION_BALANCED    = 1
Global Const $D2D1_GAUSSIANBLUR_OPTIMIZATION_QUALITY     = 2
Global Const $D2D1_GAUSSIANBLUR_OPTIMIZATION_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_DIRECTIONALBLUR_PROP
Global Const $D2D1_DIRECTIONALBLUR_PROP_STANDARD_DEVIATION = 0
Global Const $D2D1_DIRECTIONALBLUR_PROP_ANGLE              = 1
Global Const $D2D1_DIRECTIONALBLUR_PROP_OPTIMIZATION       = 2
Global Const $D2D1_DIRECTIONALBLUR_PROP_BORDER_MODE        = 3
Global Const $D2D1_DIRECTIONALBLUR_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_DIRECTIONALBLUR_OPTIMIZATION
Global Const $D2D1_DIRECTIONALBLUR_OPTIMIZATION_SPEED       = 0
Global Const $D2D1_DIRECTIONALBLUR_OPTIMIZATION_BALANCED    = 1
Global Const $D2D1_DIRECTIONALBLUR_OPTIMIZATION_QUALITY     = 2
Global Const $D2D1_DIRECTIONALBLUR_OPTIMIZATION_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_SHADOW_PROP
Global Const $D2D1_SHADOW_PROP_BLUR_STANDARD_DEVIATION = 0
Global Const $D2D1_SHADOW_PROP_COLOR                   = 1
Global Const $D2D1_SHADOW_PROP_OPTIMIZATION            = 2
Global Const $D2D1_SHADOW_PROP_FORCE_DWORD             = 0xFFFFFFFF

;# D2D1_SHADOW_OPTIMIZATION
Global Const $D2D1_SHADOW_OPTIMIZATION_SPEED       = 0
Global Const $D2D1_SHADOW_OPTIMIZATION_BALANCED    = 1
Global Const $D2D1_SHADOW_OPTIMIZATION_QUALITY     = 2
Global Const $D2D1_SHADOW_OPTIMIZATION_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_BLEND_PROP
Global Const $D2D1_BLEND_PROP_MODE        = 0
Global Const $D2D1_BLEND_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_BLEND_MODE
Global Const $D2D1_BLEND_MODE_MULTIPLY      = 0
Global Const $D2D1_BLEND_MODE_SCREEN        = 1
Global Const $D2D1_BLEND_MODE_DARKEN        = 2
Global Const $D2D1_BLEND_MODE_LIGHTEN       = 3
Global Const $D2D1_BLEND_MODE_DISSOLVE      = 4
Global Const $D2D1_BLEND_MODE_COLOR_BURN    = 5
Global Const $D2D1_BLEND_MODE_LINEAR_BURN   = 6
Global Const $D2D1_BLEND_MODE_DARKER_COLOR  = 7
Global Const $D2D1_BLEND_MODE_LIGHTER_COLOR = 8
Global Const $D2D1_BLEND_MODE_COLOR_DODGE   = 9
Global Const $D2D1_BLEND_MODE_LINEAR_DODGE  = 10
Global Const $D2D1_BLEND_MODE_OVERLAY       = 11
Global Const $D2D1_BLEND_MODE_SOFT_LIGHT    = 12
Global Const $D2D1_BLEND_MODE_HARD_LIGHT    = 13
Global Const $D2D1_BLEND_MODE_VIVID_LIGHT   = 14
Global Const $D2D1_BLEND_MODE_LINEAR_LIGHT  = 15
Global Const $D2D1_BLEND_MODE_PIN_LIGHT     = 16
Global Const $D2D1_BLEND_MODE_HARD_MIX      = 17
Global Const $D2D1_BLEND_MODE_DIFFERENCE    = 18
Global Const $D2D1_BLEND_MODE_EXCLUSION     = 19
Global Const $D2D1_BLEND_MODE_HUE           = 20
Global Const $D2D1_BLEND_MODE_SATURATION    = 21
Global Const $D2D1_BLEND_MODE_COLOR         = 22
Global Const $D2D1_BLEND_MODE_LUMINOSITY    = 23
Global Const $D2D1_BLEND_MODE_SUBTRACT      = 24
Global Const $D2D1_BLEND_MODE_DIVISION      = 25
Global Const $D2D1_BLEND_MODE_FORCE_DWORD   = 0xFFFFFFFF

;# D2D1_SATURATION_PROP
Global Const $D2D1_SATURATION_PROP_SATURATION  = 0
Global Const $D2D1_SATURATION_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_HUEROTATION_PROP
Global Const $D2D1_HUEROTATION_PROP_ANGLE       = 0
Global Const $D2D1_HUEROTATION_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_COLORMATRIX_PROP
Global Const $D2D1_COLORMATRIX_PROP_COLOR_MATRIX = 0
Global Const $D2D1_COLORMATRIX_PROP_ALPHA_MODE   = 1
Global Const $D2D1_COLORMATRIX_PROP_CLAMP_OUTPUT = 2
Global Const $D2D1_COLORMATRIX_PROP_FORCE_DWORD  = 0xFFFFFFFF

;# D2D1_COLORMATRIX_ALPHA_MODE
Global Const $D2D1_COLORMATRIX_ALPHA_MODE_PREMULTIPLIED = 1
Global Const $D2D1_COLORMATRIX_ALPHA_MODE_STRAIGHT      = 2
Global Const $D2D1_COLORMATRIX_ALPHA_MODE_FORCE_DWORD   = 0xFFFFFFFF

;# D2D1_BITMAPSOURCE_PROP
Global Const $D2D1_BITMAPSOURCE_PROP_WIC_BITMAP_SOURCE     = 0
Global Const $D2D1_BITMAPSOURCE_PROP_SCALE                 = 1
Global Const $D2D1_BITMAPSOURCE_PROP_INTERPOLATION_MODE    = 2
Global Const $D2D1_BITMAPSOURCE_PROP_ENABLE_DPI_CORRECTION = 3
Global Const $D2D1_BITMAPSOURCE_PROP_ALPHA_MODE            = 4
Global Const $D2D1_BITMAPSOURCE_PROP_ORIENTATION           = 5
Global Const $D2D1_BITMAPSOURCE_PROP_FORCE_DWORD           = 0xFFFFFFFF

;# D2D1_BITMAPSOURCE_INTERPOLATION_MODE
Global Const $D2D1_BITMAPSOURCE_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0
Global Const $D2D1_BITMAPSOURCE_INTERPOLATION_MODE_LINEAR           = 1
Global Const $D2D1_BITMAPSOURCE_INTERPOLATION_MODE_CUBIC            = 2
Global Const $D2D1_BITMAPSOURCE_INTERPOLATION_MODE_FANT             = 6
Global Const $D2D1_BITMAPSOURCE_INTERPOLATION_MODE_MIPMAP_LINEAR    = 7
Global Const $D2D1_BITMAPSOURCE_INTERPOLATION_MODE_FORCE_DWORD      = 0xFFFFFFFF

;# D2D1_BITMAPSOURCE_ALPHA_MODE
Global Const $D2D1_BITMAPSOURCE_ALPHA_MODE_PREMULTIPLIED = 1
Global Const $D2D1_BITMAPSOURCE_ALPHA_MODE_STRAIGHT      = 2
Global Const $D2D1_BITMAPSOURCE_ALPHA_MODE_FORCE_DWORD   = 0xFFFFFFFF

;# D2D1_COMPOSITE_PROP
Global Const $D2D1_COMPOSITE_PROP_MODE        = 0
Global Const $D2D1_COMPOSITE_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_3DTRANSFORM_PROP
Global Const $D2D1_3DTRANSFORM_PROP_INTERPOLATION_MODE = 0
Global Const $D2D1_3DTRANSFORM_PROP_BORDER_MODE        = 1
Global Const $D2D1_3DTRANSFORM_PROP_TRANSFORM_MATRIX   = 2
Global Const $D2D1_3DTRANSFORM_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_3DTRANSFORM_INTERPOLATION_MODE
Global Const $D2D1_3DTRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_3DTRANSFORM_INTERPOLATION_MODE_LINEAR              = 1
Global Const $D2D1_3DTRANSFORM_INTERPOLATION_MODE_CUBIC               = 2
Global Const $D2D1_3DTRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_3DTRANSFORM_INTERPOLATION_MODE_ANISOTROPIC         = 4
Global Const $D2D1_3DTRANSFORM_INTERPOLATION_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_3DPERSPECTIVETRANSFORM_PROP
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_INTERPOLATION_MODE = 0
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_BORDER_MODE        = 1
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_DEPTH              = 2
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_PERSPECTIVE_ORIGIN = 3
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_LOCAL_OFFSET       = 4
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_GLOBAL_OFFSET      = 5
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_ROTATION_ORIGIN    = 6
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_ROTATION           = 7
Global Const $D2D1_3DPERSPECTIVETRANSFORM_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE
Global Const $D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_LINEAR              = 1
Global Const $D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_CUBIC               = 2
Global Const $D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_ANISOTROPIC         = 4
Global Const $D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_2DAFFINETRANSFORM_PROP
Global Const $D2D1_2DAFFINETRANSFORM_PROP_INTERPOLATION_MODE = 0
Global Const $D2D1_2DAFFINETRANSFORM_PROP_BORDER_MODE        = 1
Global Const $D2D1_2DAFFINETRANSFORM_PROP_TRANSFORM_MATRIX   = 2
Global Const $D2D1_2DAFFINETRANSFORM_PROP_SHARPNESS          = 3
Global Const $D2D1_2DAFFINETRANSFORM_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE
Global Const $D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_LINEAR              = 1
Global Const $D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_CUBIC               = 2
Global Const $D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_ANISOTROPIC         = 4
Global Const $D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_DPICOMPENSATION_PROP
Global Const $D2D1_DPICOMPENSATION_PROP_INTERPOLATION_MODE = 0
Global Const $D2D1_DPICOMPENSATION_PROP_BORDER_MODE        = 1
Global Const $D2D1_DPICOMPENSATION_PROP_INPUT_DPI          = 2
Global Const $D2D1_DPICOMPENSATION_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_DPICOMPENSATION_INTERPOLATION_MODE
Global Const $D2D1_DPICOMPENSATION_INTERPOLATION_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_DPICOMPENSATION_INTERPOLATION_MODE_LINEAR              = 1
Global Const $D2D1_DPICOMPENSATION_INTERPOLATION_MODE_CUBIC               = 2
Global Const $D2D1_DPICOMPENSATION_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_DPICOMPENSATION_INTERPOLATION_MODE_ANISOTROPIC         = 4
Global Const $D2D1_DPICOMPENSATION_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_DPICOMPENSATION_INTERPOLATION_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_SCALE_PROP
Global Const $D2D1_SCALE_PROP_SCALE              = 0
Global Const $D2D1_SCALE_PROP_CENTER_POINT       = 1
Global Const $D2D1_SCALE_PROP_INTERPOLATION_MODE = 2
Global Const $D2D1_SCALE_PROP_BORDER_MODE        = 3
Global Const $D2D1_SCALE_PROP_SHARPNESS          = 4
Global Const $D2D1_SCALE_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_SCALE_INTERPOLATION_MODE
Global Const $D2D1_SCALE_INTERPOLATION_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_SCALE_INTERPOLATION_MODE_LINEAR              = 1
Global Const $D2D1_SCALE_INTERPOLATION_MODE_CUBIC               = 2
Global Const $D2D1_SCALE_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_SCALE_INTERPOLATION_MODE_ANISOTROPIC         = 4
Global Const $D2D1_SCALE_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_SCALE_INTERPOLATION_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_TURBULENCE_PROP
Global Const $D2D1_TURBULENCE_PROP_OFFSET         = 0
Global Const $D2D1_TURBULENCE_PROP_SIZE           = 1
Global Const $D2D1_TURBULENCE_PROP_BASE_FREQUENCY = 2
Global Const $D2D1_TURBULENCE_PROP_NUM_OCTAVES    = 3
Global Const $D2D1_TURBULENCE_PROP_SEED           = 4
Global Const $D2D1_TURBULENCE_PROP_NOISE          = 5
Global Const $D2D1_TURBULENCE_PROP_STITCHABLE     = 6
Global Const $D2D1_TURBULENCE_PROP_FORCE_DWORD    = 0xFFFFFFFF

;# D2D1_TURBULENCE_NOISE
Global Const $D2D1_TURBULENCE_NOISE_FRACTAL_SUM = 0
Global Const $D2D1_TURBULENCE_NOISE_TURBULENCE  = 1
Global Const $D2D1_TURBULENCE_NOISE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_DISPLACEMENTMAP_PROP
Global Const $D2D1_DISPLACEMENTMAP_PROP_SCALE            = 0
Global Const $D2D1_DISPLACEMENTMAP_PROP_X_CHANNEL_SELECT = 1
Global Const $D2D1_DISPLACEMENTMAP_PROP_Y_CHANNEL_SELECT = 2
Global Const $D2D1_DISPLACEMENTMAP_PROP_FORCE_DWORD      = 0xFFFFFFFF

;# D2D1_DISPLACEMENTMAP_X_CHANNEL_SELECT
Global Const $D2D1_DISPLACEMENTMAP_X_CHANNEL_SELECT_R_CHANNEL   = 0
Global Const $D2D1_DISPLACEMENTMAP_X_CHANNEL_SELECT_G_CHANNEL   = 1
Global Const $D2D1_DISPLACEMENTMAP_X_CHANNEL_SELECT_B_CHANNEL   = 2
Global Const $D2D1_DISPLACEMENTMAP_X_CHANNEL_SELECT_A_CHANNEL   = 3
Global Const $D2D1_DISPLACEMENTMAP_X_CHANNEL_SELECT_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_DISPLACEMENTMAP_Y_CHANNEL_SELECT
Global Const $D2D1_DISPLACEMENTMAP_Y_CHANNEL_SELECT_R_CHANNEL   = 0
Global Const $D2D1_DISPLACEMENTMAP_Y_CHANNEL_SELECT_G_CHANNEL   = 1
Global Const $D2D1_DISPLACEMENTMAP_Y_CHANNEL_SELECT_B_CHANNEL   = 2
Global Const $D2D1_DISPLACEMENTMAP_Y_CHANNEL_SELECT_A_CHANNEL   = 3
Global Const $D2D1_DISPLACEMENTMAP_Y_CHANNEL_SELECT_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_COLORMANAGEMENT_PROP
Global Const $D2D1_COLORMANAGEMENT_PROP_SOURCE_COLOR_CONTEXT         = 0
Global Const $D2D1_COLORMANAGEMENT_PROP_SOURCE_RENDERING_INTENT      = 1
Global Const $D2D1_COLORMANAGEMENT_PROP_DESTINATION_COLOR_CONTEXT    = 2
Global Const $D2D1_COLORMANAGEMENT_PROP_DESTINATION_RENDERING_INTENT = 3
Global Const $D2D1_COLORMANAGEMENT_PROP_ALPHA_MODE                   = 4
Global Const $D2D1_COLORMANAGEMENT_PROP_FORCE_DWORD                  = 0xFFFFFFFF

;# D2D1_COLORMANAGEMENT_ALPHA_MODE
Global Const $D2D1_COLORMANAGEMENT_ALPHA_MODE_PREMULTIPLIED = 1
Global Const $D2D1_COLORMANAGEMENT_ALPHA_MODE_STRAIGHT      = 2
Global Const $D2D1_COLORMANAGEMENT_ALPHA_MODE_FORCE_DWORD   = 0xFFFFFFFF

;# D2D1_COLORMANAGEMENT_RENDERING_INTENT
Global Const $D2D1_COLORMANAGEMENT_RENDERING_INTENT_PERCEPTUAL            = 0
Global Const $D2D1_COLORMANAGEMENT_RENDERING_INTENT_RELATIVE_COLORIMETRIC = 1
Global Const $D2D1_COLORMANAGEMENT_RENDERING_INTENT_SATURATION            = 2
Global Const $D2D1_COLORMANAGEMENT_RENDERING_INTENT_ABSOLUTE_COLORIMETRIC = 3
Global Const $D2D1_COLORMANAGEMENT_RENDERING_INTENT_FORCE_DWORD           = 0xFFFFFFFF

;# D2D1_HISTOGRAM_PROP
Global Const $D2D1_HISTOGRAM_PROP_NUM_BINS         = 0
Global Const $D2D1_HISTOGRAM_PROP_CHANNEL_SELECT   = 1
Global Const $D2D1_HISTOGRAM_PROP_HISTOGRAM_OUTPUT = 2
Global Const $D2D1_HISTOGRAM_PROP_FORCE_DWORD      = 0xFFFFFFFF

;# D2D1_POINTSPECULAR_PROP
Global Const $D2D1_POINTSPECULAR_PROP_LIGHT_POSITION     = 0
Global Const $D2D1_POINTSPECULAR_PROP_SPECULAR_EXPONENT  = 1
Global Const $D2D1_POINTSPECULAR_PROP_SPECULAR_CONSTANT  = 2
Global Const $D2D1_POINTSPECULAR_PROP_SURFACE_SCALE      = 3
Global Const $D2D1_POINTSPECULAR_PROP_COLOR              = 4
Global Const $D2D1_POINTSPECULAR_PROP_KERNEL_UNIT_LENGTH = 5
Global Const $D2D1_POINTSPECULAR_PROP_SCALE_MODE         = 6
Global Const $D2D1_POINTSPECULAR_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_POINTSPECULAR_SCALE_MODE
Global Const $D2D1_POINTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_POINTSPECULAR_SCALE_MODE_LINEAR              = 1
Global Const $D2D1_POINTSPECULAR_SCALE_MODE_CUBIC               = 2
Global Const $D2D1_POINTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_POINTSPECULAR_SCALE_MODE_ANISOTROPIC         = 4
Global Const $D2D1_POINTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_POINTSPECULAR_SCALE_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_SPOTSPECULAR_PROP
Global Const $D2D1_SPOTSPECULAR_PROP_LIGHT_POSITION      = 0
Global Const $D2D1_SPOTSPECULAR_PROP_POINTS_AT           = 1
Global Const $D2D1_SPOTSPECULAR_PROP_FOCUS               = 2
Global Const $D2D1_SPOTSPECULAR_PROP_LIMITING_CONE_ANGLE = 3
Global Const $D2D1_SPOTSPECULAR_PROP_SPECULAR_EXPONENT   = 4
Global Const $D2D1_SPOTSPECULAR_PROP_SPECULAR_CONSTANT   = 5
Global Const $D2D1_SPOTSPECULAR_PROP_SURFACE_SCALE       = 6
Global Const $D2D1_SPOTSPECULAR_PROP_COLOR               = 7
Global Const $D2D1_SPOTSPECULAR_PROP_KERNEL_UNIT_LENGTH  = 8
Global Const $D2D1_SPOTSPECULAR_PROP_SCALE_MODE          = 9
Global Const $D2D1_SPOTSPECULAR_PROP_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_SPOTSPECULAR_SCALE_MODE
Global Const $D2D1_SPOTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_SPOTSPECULAR_SCALE_MODE_LINEAR              = 1
Global Const $D2D1_SPOTSPECULAR_SCALE_MODE_CUBIC               = 2
Global Const $D2D1_SPOTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_SPOTSPECULAR_SCALE_MODE_ANISOTROPIC         = 4
Global Const $D2D1_SPOTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_SPOTSPECULAR_SCALE_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_DISTANTSPECULAR_PROP
Global Const $D2D1_DISTANTSPECULAR_PROP_AZIMUTH            = 0
Global Const $D2D1_DISTANTSPECULAR_PROP_ELEVATION          = 1
Global Const $D2D1_DISTANTSPECULAR_PROP_SPECULAR_EXPONENT  = 2
Global Const $D2D1_DISTANTSPECULAR_PROP_SPECULAR_CONSTANT  = 3
Global Const $D2D1_DISTANTSPECULAR_PROP_SURFACE_SCALE      = 4
Global Const $D2D1_DISTANTSPECULAR_PROP_COLOR              = 5
Global Const $D2D1_DISTANTSPECULAR_PROP_KERNEL_UNIT_LENGTH = 6
Global Const $D2D1_DISTANTSPECULAR_PROP_SCALE_MODE         = 7
Global Const $D2D1_DISTANTSPECULAR_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_DISTANTSPECULAR_SCALE_MODE
Global Const $D2D1_DISTANTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_DISTANTSPECULAR_SCALE_MODE_LINEAR              = 1
Global Const $D2D1_DISTANTSPECULAR_SCALE_MODE_CUBIC               = 2
Global Const $D2D1_DISTANTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_DISTANTSPECULAR_SCALE_MODE_ANISOTROPIC         = 4
Global Const $D2D1_DISTANTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_DISTANTSPECULAR_SCALE_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_POINTDIFFUSE_PROP
Global Const $D2D1_POINTDIFFUSE_PROP_LIGHT_POSITION     = 0
Global Const $D2D1_POINTDIFFUSE_PROP_DIFFUSE_CONSTANT   = 1
Global Const $D2D1_POINTDIFFUSE_PROP_SURFACE_SCALE      = 2
Global Const $D2D1_POINTDIFFUSE_PROP_COLOR              = 3
Global Const $D2D1_POINTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 4
Global Const $D2D1_POINTDIFFUSE_PROP_SCALE_MODE         = 5
Global Const $D2D1_POINTDIFFUSE_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_POINTDIFFUSE_SCALE_MODE
Global Const $D2D1_POINTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_POINTDIFFUSE_SCALE_MODE_LINEAR              = 1
Global Const $D2D1_POINTDIFFUSE_SCALE_MODE_CUBIC               = 2
Global Const $D2D1_POINTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_POINTDIFFUSE_SCALE_MODE_ANISOTROPIC         = 4
Global Const $D2D1_POINTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_POINTDIFFUSE_SCALE_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_SPOTDIFFUSE_PROP
Global Const $D2D1_SPOTDIFFUSE_PROP_LIGHT_POSITION      = 0
Global Const $D2D1_SPOTDIFFUSE_PROP_POINTS_AT           = 1
Global Const $D2D1_SPOTDIFFUSE_PROP_FOCUS               = 2
Global Const $D2D1_SPOTDIFFUSE_PROP_LIMITING_CONE_ANGLE = 3
Global Const $D2D1_SPOTDIFFUSE_PROP_DIFFUSE_CONSTANT    = 4
Global Const $D2D1_SPOTDIFFUSE_PROP_SURFACE_SCALE       = 5
Global Const $D2D1_SPOTDIFFUSE_PROP_COLOR               = 6
Global Const $D2D1_SPOTDIFFUSE_PROP_KERNEL_UNIT_LENGTH  = 7
Global Const $D2D1_SPOTDIFFUSE_PROP_SCALE_MODE          = 8
Global Const $D2D1_SPOTDIFFUSE_PROP_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_SPOTDIFFUSE_SCALE_MODE
Global Const $D2D1_SPOTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_SPOTDIFFUSE_SCALE_MODE_LINEAR              = 1
Global Const $D2D1_SPOTDIFFUSE_SCALE_MODE_CUBIC               = 2
Global Const $D2D1_SPOTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_SPOTDIFFUSE_SCALE_MODE_ANISOTROPIC         = 4
Global Const $D2D1_SPOTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_SPOTDIFFUSE_SCALE_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_DISTANTDIFFUSE_PROP
Global Const $D2D1_DISTANTDIFFUSE_PROP_AZIMUTH            = 0
Global Const $D2D1_DISTANTDIFFUSE_PROP_ELEVATION          = 1
Global Const $D2D1_DISTANTDIFFUSE_PROP_DIFFUSE_CONSTANT   = 2
Global Const $D2D1_DISTANTDIFFUSE_PROP_SURFACE_SCALE      = 3
Global Const $D2D1_DISTANTDIFFUSE_PROP_COLOR              = 4
Global Const $D2D1_DISTANTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 5
Global Const $D2D1_DISTANTDIFFUSE_PROP_SCALE_MODE         = 6
Global Const $D2D1_DISTANTDIFFUSE_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_DISTANTDIFFUSE_SCALE_MODE
Global Const $D2D1_DISTANTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_DISTANTDIFFUSE_SCALE_MODE_LINEAR              = 1
Global Const $D2D1_DISTANTDIFFUSE_SCALE_MODE_CUBIC               = 2
Global Const $D2D1_DISTANTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_DISTANTDIFFUSE_SCALE_MODE_ANISOTROPIC         = 4
Global Const $D2D1_DISTANTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_DISTANTDIFFUSE_SCALE_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_FLOOD_PROP
Global Const $D2D1_FLOOD_PROP_COLOR       = 0
Global Const $D2D1_FLOOD_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_LINEARTRANSFER_PROP
Global Const $D2D1_LINEARTRANSFER_PROP_RED_Y_INTERCEPT   = 0
Global Const $D2D1_LINEARTRANSFER_PROP_RED_SLOPE         = 1
Global Const $D2D1_LINEARTRANSFER_PROP_RED_DISABLE       = 2
Global Const $D2D1_LINEARTRANSFER_PROP_GREEN_Y_INTERCEPT = 3
Global Const $D2D1_LINEARTRANSFER_PROP_GREEN_SLOPE       = 4
Global Const $D2D1_LINEARTRANSFER_PROP_GREEN_DISABLE     = 5
Global Const $D2D1_LINEARTRANSFER_PROP_BLUE_Y_INTERCEPT  = 6
Global Const $D2D1_LINEARTRANSFER_PROP_BLUE_SLOPE        = 7
Global Const $D2D1_LINEARTRANSFER_PROP_BLUE_DISABLE      = 8
Global Const $D2D1_LINEARTRANSFER_PROP_ALPHA_Y_INTERCEPT = 9
Global Const $D2D1_LINEARTRANSFER_PROP_ALPHA_SLOPE       = 10
Global Const $D2D1_LINEARTRANSFER_PROP_ALPHA_DISABLE     = 11
Global Const $D2D1_LINEARTRANSFER_PROP_CLAMP_OUTPUT      = 12
Global Const $D2D1_LINEARTRANSFER_PROP_FORCE_DWORD       = 0xFFFFFFFF

;# D2D1_GAMMATRANSFER_PROP
Global Const $D2D1_GAMMATRANSFER_PROP_RED_AMPLITUDE   = 0
Global Const $D2D1_GAMMATRANSFER_PROP_RED_EXPONENT    = 1
Global Const $D2D1_GAMMATRANSFER_PROP_RED_OFFSET      = 2
Global Const $D2D1_GAMMATRANSFER_PROP_RED_DISABLE     = 3
Global Const $D2D1_GAMMATRANSFER_PROP_GREEN_AMPLITUDE = 4
Global Const $D2D1_GAMMATRANSFER_PROP_GREEN_EXPONENT  = 5
Global Const $D2D1_GAMMATRANSFER_PROP_GREEN_OFFSET    = 6
Global Const $D2D1_GAMMATRANSFER_PROP_GREEN_DISABLE   = 7
Global Const $D2D1_GAMMATRANSFER_PROP_BLUE_AMPLITUDE  = 8
Global Const $D2D1_GAMMATRANSFER_PROP_BLUE_EXPONENT   = 9
Global Const $D2D1_GAMMATRANSFER_PROP_BLUE_OFFSET     = 10
Global Const $D2D1_GAMMATRANSFER_PROP_BLUE_DISABLE    = 11
Global Const $D2D1_GAMMATRANSFER_PROP_ALPHA_AMPLITUDE = 12
Global Const $D2D1_GAMMATRANSFER_PROP_ALPHA_EXPONENT  = 13
Global Const $D2D1_GAMMATRANSFER_PROP_ALPHA_OFFSET    = 14
Global Const $D2D1_GAMMATRANSFER_PROP_ALPHA_DISABLE   = 15
Global Const $D2D1_GAMMATRANSFER_PROP_CLAMP_OUTPUT    = 16
Global Const $D2D1_GAMMATRANSFER_PROP_FORCE_DWORD     = 0xFFFFFFFF

;# D2D1_TABLETRANSFER_PROP
Global Const $D2D1_TABLETRANSFER_PROP_RED_TABLE     = 0
Global Const $D2D1_TABLETRANSFER_PROP_RED_DISABLE   = 1
Global Const $D2D1_TABLETRANSFER_PROP_GREEN_TABLE   = 2
Global Const $D2D1_TABLETRANSFER_PROP_GREEN_DISABLE = 3
Global Const $D2D1_TABLETRANSFER_PROP_BLUE_TABLE    = 4
Global Const $D2D1_TABLETRANSFER_PROP_BLUE_DISABLE  = 5
Global Const $D2D1_TABLETRANSFER_PROP_ALPHA_TABLE   = 6
Global Const $D2D1_TABLETRANSFER_PROP_ALPHA_DISABLE = 7
Global Const $D2D1_TABLETRANSFER_PROP_CLAMP_OUTPUT  = 8
Global Const $D2D1_TABLETRANSFER_PROP_FORCE_DWORD   = 0xFFFFFFFF

;# D2D1_DISCRETETRANSFER_PROP
Global Const $D2D1_DISCRETETRANSFER_PROP_RED_TABLE     = 0
Global Const $D2D1_DISCRETETRANSFER_PROP_RED_DISABLE   = 1
Global Const $D2D1_DISCRETETRANSFER_PROP_GREEN_TABLE   = 2
Global Const $D2D1_DISCRETETRANSFER_PROP_GREEN_DISABLE = 3
Global Const $D2D1_DISCRETETRANSFER_PROP_BLUE_TABLE    = 4
Global Const $D2D1_DISCRETETRANSFER_PROP_BLUE_DISABLE  = 5
Global Const $D2D1_DISCRETETRANSFER_PROP_ALPHA_TABLE   = 6
Global Const $D2D1_DISCRETETRANSFER_PROP_ALPHA_DISABLE = 7
Global Const $D2D1_DISCRETETRANSFER_PROP_CLAMP_OUTPUT  = 8
Global Const $D2D1_DISCRETETRANSFER_PROP_FORCE_DWORD   = 0xFFFFFFFF

;# D2D1_CONVOLVEMATRIX_PROP
Global Const $D2D1_CONVOLVEMATRIX_PROP_KERNEL_UNIT_LENGTH = 0
Global Const $D2D1_CONVOLVEMATRIX_PROP_SCALE_MODE         = 1
Global Const $D2D1_CONVOLVEMATRIX_PROP_KERNEL_SIZE_X      = 2
Global Const $D2D1_CONVOLVEMATRIX_PROP_KERNEL_SIZE_Y      = 3
Global Const $D2D1_CONVOLVEMATRIX_PROP_KERNEL_MATRIX      = 4
Global Const $D2D1_CONVOLVEMATRIX_PROP_DIVISOR            = 5
Global Const $D2D1_CONVOLVEMATRIX_PROP_BIAS               = 6
Global Const $D2D1_CONVOLVEMATRIX_PROP_KERNEL_OFFSET      = 7
Global Const $D2D1_CONVOLVEMATRIX_PROP_PRESERVE_ALPHA     = 8
Global Const $D2D1_CONVOLVEMATRIX_PROP_BORDER_MODE        = 9
Global Const $D2D1_CONVOLVEMATRIX_PROP_CLAMP_OUTPUT       = 10
Global Const $D2D1_CONVOLVEMATRIX_PROP_FORCE_DWORD        = 0xFFFFFFFF

;# D2D1_CONVOLVEMATRIX_SCALE_MODE
Global Const $D2D1_CONVOLVEMATRIX_SCALE_MODE_NEAREST_NEIGHBOR    = 0
Global Const $D2D1_CONVOLVEMATRIX_SCALE_MODE_LINEAR              = 1
Global Const $D2D1_CONVOLVEMATRIX_SCALE_MODE_CUBIC               = 2
Global Const $D2D1_CONVOLVEMATRIX_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3
Global Const $D2D1_CONVOLVEMATRIX_SCALE_MODE_ANISOTROPIC         = 4
Global Const $D2D1_CONVOLVEMATRIX_SCALE_MODE_HIGH_QUALITY_CUBIC  = 5
Global Const $D2D1_CONVOLVEMATRIX_SCALE_MODE_FORCE_DWORD         = 0xFFFFFFFF

;# D2D1_BRIGHTNESS_PROP
Global Const $D2D1_BRIGHTNESS_PROP_WHITE_POINT = 0
Global Const $D2D1_BRIGHTNESS_PROP_BLACK_POINT = 1
Global Const $D2D1_BRIGHTNESS_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_ARITHMETICCOMPOSITE_PROP
Global Const $D2D1_ARITHMETICCOMPOSITE_PROP_COEFFICIENTS = 0
Global Const $D2D1_ARITHMETICCOMPOSITE_PROP_CLAMP_OUTPUT = 1
Global Const $D2D1_ARITHMETICCOMPOSITE_PROP_FORCE_DWORD  = 0xFFFFFFFF

;# D2D1_CROP_PROP
Global Const $D2D1_CROP_PROP_RECT        = 0
Global Const $D2D1_CROP_PROP_BORDER_MODE = 1
Global Const $D2D1_CROP_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_BORDER_PROP
Global Const $D2D1_BORDER_PROP_EDGE_MODE_X = 0
Global Const $D2D1_BORDER_PROP_EDGE_MODE_Y = 1
Global Const $D2D1_BORDER_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_BORDER_EDGE_MODE
Global Const $D2D1_BORDER_EDGE_MODE_CLAMP       = 0
Global Const $D2D1_BORDER_EDGE_MODE_WRAP        = 1
Global Const $D2D1_BORDER_EDGE_MODE_MIRROR      = 2
Global Const $D2D1_BORDER_EDGE_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_MORPHOLOGY_PROP
Global Const $D2D1_MORPHOLOGY_PROP_MODE        = 0
Global Const $D2D1_MORPHOLOGY_PROP_WIDTH       = 1
Global Const $D2D1_MORPHOLOGY_PROP_HEIGHT      = 2
Global Const $D2D1_MORPHOLOGY_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_MORPHOLOGY_MODE
Global Const $D2D1_MORPHOLOGY_MODE_ERODE       = 0
Global Const $D2D1_MORPHOLOGY_MODE_DILATE      = 1
Global Const $D2D1_MORPHOLOGY_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_TILE_PROP
Global Const $D2D1_TILE_PROP_RECT        = 0
Global Const $D2D1_TILE_PROP_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_ATLAS_PROP
Global Const $D2D1_ATLAS_PROP_INPUT_RECT         = 0
Global Const $D2D1_ATLAS_PROP_INPUT_PADDING_RECT = 1
Global Const $D2D1_ATLAS_PROP_FORCE_DWORD        = 0xFFFFFFFF



















;############################################################################################################
;# D2D1_1_Enumerations
;############################################################################################################

;# D2D1_PROPERTY_TYPE
Global Const $D2D1_PROPERTY_TYPE_UNKNOWN = 0
Global Const $D2D1_PROPERTY_TYPE_STRING = 1
Global Const $D2D1_PROPERTY_TYPE_BOOL = 2
Global Const $D2D1_PROPERTY_TYPE_UINT32 = 3
Global Const $D2D1_PROPERTY_TYPE_INT32 = 4
Global Const $D2D1_PROPERTY_TYPE_FLOAT = 5
Global Const $D2D1_PROPERTY_TYPE_VECTOR2 = 6
Global Const $D2D1_PROPERTY_TYPE_VECTOR3 = 7
Global Const $D2D1_PROPERTY_TYPE_VECTOR4 = 8
Global Const $D2D1_PROPERTY_TYPE_BLOB = 9
Global Const $D2D1_PROPERTY_TYPE_IUNKNOWN = 10
Global Const $D2D1_PROPERTY_TYPE_ENUM = 11
Global Const $D2D1_PROPERTY_TYPE_ARRAY = 12
Global Const $D2D1_PROPERTY_TYPE_CLSID = 13
Global Const $D2D1_PROPERTY_TYPE_MATRIX_3X2 = 14
Global Const $D2D1_PROPERTY_TYPE_MATRIX_4X3 = 15
Global Const $D2D1_PROPERTY_TYPE_MATRIX_4X4 = 16
Global Const $D2D1_PROPERTY_TYPE_MATRIX_5X4 = 17
Global Const $D2D1_PROPERTY_TYPE_COLOR_CONTEXT = 18
Global Const $D2D1_PROPERTY_TYPE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_PROPERTY
Global Const $D2D1_PROPERTY_CLSID = 0x80000000
Global Const $D2D1_PROPERTY_DISPLAYNAME = 0x80000001
Global Const $D2D1_PROPERTY_AUTHOR = 0x80000002
Global Const $D2D1_PROPERTY_CATEGORY = 0x80000003
Global Const $D2D1_PROPERTY_DESCRIPTION = 0x80000004
Global Const $D2D1_PROPERTY_INPUTS = 0x80000005
Global Const $D2D1_PROPERTY_CACHED = 0x80000006
Global Const $D2D1_PROPERTY_PRECISION = 0x80000007
Global Const $D2D1_PROPERTY_MIN_INPUTS = 0x80000008
Global Const $D2D1_PROPERTY_MAX_INPUTS = 0x80000009
Global Const $D2D1_PROPERTY_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_SUBPROPERTY
Global Const $D2D1_SUBPROPERTY_DISPLAYNAME = 0x80000000
Global Const $D2D1_SUBPROPERTY_ISREADONLY = 0x80000001
Global Const $D2D1_SUBPROPERTY_MIN = 0x80000002
Global Const $D2D1_SUBPROPERTY_MAX = 0x80000003
Global Const $D2D1_SUBPROPERTY_DEFAULT = 0x80000004
Global Const $D2D1_SUBPROPERTY_FIELDS = 0x80000005
Global Const $D2D1_SUBPROPERTY_INDEX = 0x80000006
Global Const $D2D1_SUBPROPERTY_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_BITMAP_OPTIONS
Global Const $D2D1_BITMAP_OPTIONS_NONE = 0x00000000
Global Const $D2D1_BITMAP_OPTIONS_TARGET = 0x00000001
Global Const $D2D1_BITMAP_OPTIONS_CANNOT_DRAW = 0x00000002
Global Const $D2D1_BITMAP_OPTIONS_CPU_READ = 0x00000004
Global Const $D2D1_BITMAP_OPTIONS_GDI_COMPATIBLE = 0x00000008
Global Const $D2D1_BITMAP_OPTIONS_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_COMPOSITE_MODE
Global Const $D2D1_COMPOSITE_MODE_SOURCE_OVER = 0
Global Const $D2D1_COMPOSITE_MODE_DESTINATION_OVER = 1
Global Const $D2D1_COMPOSITE_MODE_SOURCE_IN = 2
Global Const $D2D1_COMPOSITE_MODE_DESTINATION_IN = 3
Global Const $D2D1_COMPOSITE_MODE_SOURCE_OUT = 4
Global Const $D2D1_COMPOSITE_MODE_DESTINATION_OUT = 5
Global Const $D2D1_COMPOSITE_MODE_SOURCE_ATOP = 6
Global Const $D2D1_COMPOSITE_MODE_DESTINATION_ATOP = 7
Global Const $D2D1_COMPOSITE_MODE_XOR = 8
Global Const $D2D1_COMPOSITE_MODE_PLUS = 9
Global Const $D2D1_COMPOSITE_MODE_SOURCE_COPY = 10
Global Const $D2D1_COMPOSITE_MODE_BOUNDED_SOURCE_COPY = 11
Global Const $D2D1_COMPOSITE_MODE_MASK_INVERT = 12
Global Const $D2D1_COMPOSITE_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_BUFFER_PRECISION
Global Const $D2D1_BUFFER_PRECISION_UNKNOWN = 0
Global Const $D2D1_BUFFER_PRECISION_8BPC_UNORM = 1
Global Const $D2D1_BUFFER_PRECISION_8BPC_UNORM_SRGB = 2
Global Const $D2D1_BUFFER_PRECISION_16BPC_UNORM = 3
Global Const $D2D1_BUFFER_PRECISION_16BPC_FLOAT = 4
Global Const $D2D1_BUFFER_PRECISION_32BPC_FLOAT = 5
Global Const $D2D1_BUFFER_PRECISION_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_MAP_OPTIONS
Global Const $D2D1_MAP_OPTIONS_NONE = 0
Global Const $D2D1_MAP_OPTIONS_READ = 1
Global Const $D2D1_MAP_OPTIONS_WRITE = 2
Global Const $D2D1_MAP_OPTIONS_DISCARD = 4
Global Const $D2D1_MAP_OPTIONS_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_INTERPOLATION_MODE
Global Const $D2D1_INTERPOLATION_MODE_NEAREST_NEIGHBOR = $D2D1_INTERPOLATION_MODE_DEFINITION_NEAREST_NEIGHBOR
Global Const $D2D1_INTERPOLATION_MODE_LINEAR = $D2D1_INTERPOLATION_MODE_DEFINITION_LINEAR
Global Const $D2D1_INTERPOLATION_MODE_CUBIC = $D2D1_INTERPOLATION_MODE_DEFINITION_CUBIC
Global Const $D2D1_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = $D2D1_INTERPOLATION_MODE_DEFINITION_MULTI_SAMPLE_LINEAR
Global Const $D2D1_INTERPOLATION_MODE_ANISOTROPIC = $D2D1_INTERPOLATION_MODE_DEFINITION_ANISOTROPIC
Global Const $D2D1_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC = $D2D1_INTERPOLATION_MODE_DEFINITION_HIGH_QUALITY_CUBIC
Global Const $D2D1_INTERPOLATION_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_UNIT_MODE
Global Const $D2D1_UNIT_MODE_DIPS = 0
Global Const $D2D1_UNIT_MODE_PIXELS = 1
Global Const $D2D1_UNIT_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_COLOR_SPACE
Global Const $D2D1_COLOR_SPACE_CUSTOM = 0
Global Const $D2D1_COLOR_SPACE_SRGB = 1
Global Const $D2D1_COLOR_SPACE_SCRGB = 2
Global Const $D2D1_COLOR_SPACE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_DEVICE_CONTEXT_OPTIONS
Global Const $D2D1_DEVICE_CONTEXT_OPTIONS_NONE = 0
Global Const $D2D1_DEVICE_CONTEXT_OPTIONS_ENABLE_MULTITHREADED_OPTIMIZATIONS = 1
Global Const $D2D1_DEVICE_CONTEXT_OPTIONS_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_STROKE_TRANSFORM_TYPE
Global Const $D2D1_STROKE_TRANSFORM_TYPE_NORMAL = 0
Global Const $D2D1_STROKE_TRANSFORM_TYPE_FIXED = 1
Global Const $D2D1_STROKE_TRANSFORM_TYPE_HAIRLINE = 2
Global Const $D2D1_STROKE_TRANSFORM_TYPE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_PRIMITIVE_BLEND
Global Const $D2D1_PRIMITIVE_BLEND_SOURCE_OVER = 0
Global Const $D2D1_PRIMITIVE_BLEND_COPY = 1
Global Const $D2D1_PRIMITIVE_BLEND_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_THREADING_MODE
Global Const $D2D1_THREADING_MODE_SINGLE_THREADED = $D2D1_FACTORY_TYPE_SINGLE_THREADED
Global Const $D2D1_THREADING_MODE_MULTI_THREADED = $D2D1_FACTORY_TYPE_MULTI_THREADED
Global Const $D2D1_THREADING_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_COLOR_INTERPOLATION_MODE
Global Const $D2D1_COLOR_INTERPOLATION_MODE_STRAIGHT = 0
Global Const $D2D1_COLOR_INTERPOLATION_MODE_PREMULTIPLIED = 1
Global Const $D2D1_COLOR_INTERPOLATION_MODE_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_LAYER_OPTIONS1
Global Const $D2D1_LAYER_OPTIONS1_NONE = 0
Global Const $D2D1_LAYER_OPTIONS1_INITIALIZE_FROM_BACKGROUND = 1
Global Const $D2D1_LAYER_OPTIONS1_IGNORE_ALPHA = 2
Global Const $D2D1_LAYER_OPTIONS1_FORCE_DWORD = 0xFFFFFFFF

;# D2D1_PRINT_FONT_SUBSET_MODE
Global Const $D2D1_PRINT_FONT_SUBSET_MODE_DEFAULT = 0
Global Const $D2D1_PRINT_FONT_SUBSET_MODE_EACHPAGE = 1
Global Const $D2D1_PRINT_FONT_SUBSET_MODE_NONE = 2
Global Const $D2D1_PRINT_FONT_SUBSET_MODE_FORCE_DWORD = 0xFFFFFFFF






;############################################################################################################
;# D2D1_1_BASETYPES
;############################################################################################################
Global Const $tagD2D1_RECT_L = "struct; int Left; int Top; int Right; int Bottom; endstruct;"
Global Const $tagD2D1_POINT_2L = "struct; int X; int Y; endstruct;"
Global Const $tagD2D1_VECTOR_2F = "struct; float X; float Y; endstruct;"
Global Const $tagD2D1_VECTOR_3F = "struct; float X; float Y; float Z; endstruct;"
Global Const $tagD2D1_VECTOR_4F = "struct; float X; float Y; float Z; float W; endstruct;"

Global Const $tagD2D1_MATRIX_4X4_F = "struct; float M1[4]; float M2[4]; float M3[4]; float M4[4]; endstruct;"




;############################################################################################################
;# D2D1_1_STRUCTURES
;############################################################################################################
Global Const $tagD2D1_BITMAP_PROPERTIES1 = "struct; uint Pixelformat; uint AlphaMode; float DpiX; float DpiY; uint Bitmapoptions; ptr Colorcontext; endstruct;"
Global Const $tagD2D1_MAPPED_RECT = "struct; uint Pitch; ptr Bits; endstruct;"
Global Const $tagD2D1_RENDERING_CONTROLS = "struct; uint Bufferprecision; uint TilesizeW; uint TilesizeH; endstruct;"
Global Const $tagD2D1_EFFECT_INPUT_DESCRIPTION = "struct; ptr Effect; uint Inputindex; float Left; float Top; float Right; float Bottom; endstruct;"
Global Const $tagD2D1_POINT_DESCRIPTION = "struct; float X; float Y; float VX; float VY; uint Endsegment; uint Endfigure; float Lengthtoendsegment; endstruct;"
Global Const $tagD2D1_IMAGE_BRUSH_PROPERTIES = "struct; float Left; float Top; float Right; float Bottom; uint ExtendmodeX; uint ExtendmodeY; uint Interpolationmode; endstruct;"
Global Const $tagD2D1_BITMAP_BRUSH_PROPERTIES1 = "struct; uint ExtendmodeX; uint ExtendmodeY; uint Interpolationmode; endstruct;"
Global Const $tagD2D1_STROKE_STYLE_PROPERTIES1 = "struct; uint Startcap; uint Endcap; uint Dashcap; uint Linejoin; float Miterlimit; uint Dashstyle; float Dashoffset; uint Transformtype; endstruct;"
Global Const $tagD2D1_LAYER_PARAMETERS1 = "struct; float Left; float Top; float Right; float Bottom; ptr Geometricmask; uint Maskantialiasmode; float M11; float M12; float M21; float M22; float M31; float M32; float Opacity; ptr Opacitybrush; uint Layeroptions; endstruct;"
Global Const $tagD2D1_DRAWING_STATE_DESCRIPTION1 = "struct; uint Antialiasmode; uint Textantialiasmode; uint64 Tag1; uint64 Tag2; float M11; float M12; float M21; float M22; float M31; float M32; uint Primitiveblend; uint Unitmode; endstruct;"
Global Const $tagD2D1_PRINT_CONTROL_PROPERTIES = "struct; uint Fontsubset; float Rasterdpi; uint Colorspace; endstruct;"
Global Const $tagD2D1_CREATION_PROPERTIES = "struct; uint Threadingmode; uint Debuglevel; uint Options; endstruct;"







;############################################################################################################
;# D2D1_1_GUID
;############################################################################################################
Global Const $sIID_ID2D1GdiMetafileSink = "{82237326-8111-4f7c-bcf4-b5c1175564fe}"
Global Const $sIID_ID2D1GdiMetafile = "{2f543dc3-cfc1-4211-864f-cfd91c6f3395}"
Global Const $sIID_ID2D1CommandSink = "{54d7898a-a061-40a7-bec7-e465bcba2c4f}"
Global Const $sIID_ID2D1CommandList = "{b4f34a19-2383-4d76-94f6-ec343657c3dc}"
Global Const $sIID_ID2D1PrintControl = "{2c1d867d-c290-41c8-ae7e-34a98702e9a5}"
Global Const $sIID_ID2D1ImageBrush = "{fe9e984d-3f95-407c-b5db-cb94d4e8f87c}"
Global Const $sIID_ID2D1BitmapBrush1 = "{41343a53-e41a-49a2-91cd-21793bbb62e5}"
Global Const $sIID_ID2D1StrokeStyle1 = "{10a72a66-e91c-43f4-993f-ddf4b82b0b4a}"
Global Const $sIID_ID2D1PathGeometry1 = "{62baa2d2-ab54-41b7-b872-787e0106a421}"
Global Const $sIID_ID2D1Properties = "{483473d7-cd46-4f9d-9d3a-3112aa80159d}"
Global Const $sIID_ID2D1Effect = "{28211a43-7d89-476f-8181-2d6159b220ad}"
Global Const $sIID_ID2D1Bitmap1 = "{a898a84c-3873-4588-b08b-ebbf978df041}"
Global Const $sIID_ID2D1ColorContext = "{1c4820bb-5771-4518-a581-2fe4dd0ec657}"
Global Const $sIID_ID2D1GradientStopCollection1 = "{ae1572f4-5dd0-4777-998b-9279472ae63b}"
Global Const $sIID_ID2D1DrawingStateBlock1 = "{689f1f85-c72e-4e33-8f19-85754efd5ace}"
Global Const $sIID_ID2D1DeviceContext = "{e8f7fe7a-191c-466d-ad95-975678bda998}"
Global Const $sIID_ID2D1Device = "{47dd575d-ac05-4cdd-8049-9b02cd16f44c}"
Global Const $sIID_ID2D1Factory1 = "{bb12d362-daee-4b9a-aa1d-14ba401cfa1f}"
Global Const $sIID_ID2D1Image = "{65019f75-8da2-497c-b32c-dfa34e48ede6}"







;############################################################################################################
;# D2D1_1_InterfaceDescription
;############################################################################################################
Global Const $tagID2D1Image = $tagID2D1Resource

Global Const $tagID2D1GdiMetafileSink = "ProcessRecord hresult(uint;struct*;uint);"

Global Const $tagID2D1GdiMetafile = $tagID2D1Resource & _
		"Stream hresult(struct*);" & _
		"GetBounds hresult(struct*);"

Global Const $tagID2D1CommandSink = "BeginDraw hresult();" & _
		"EndDraw hresult();" & _
		"SetAntialiasMode hresult(uint);" & _
		"SetTags hresult(uint64;uint64);" & _
		"SetTextAntialiasMode hresult(uint);" & _
		"SetTextRenderingParams hresult(struct*);" & _
		"SetTransform hresult(struct*);" & _
		"SetPrimitiveBlend hresult(uint);" & _
		"SetUnitMode hresult(uint);" & _
		"Clear hresult(struct*);" & _
		"DrawGlyphRun hresult(float;float;struct*;struct*;struct*;uint);" & _
		"DrawLine hresult(float;float;float;float;struct*;float;struct*);" & _
		"DrawGeometry hresult(struct*;struct*;float;struct*);" & _
		"DrawRectangle hresult(struct*;struct*;float;struct*);" & _
		"DrawBitmap hresult(struct*;struct*;float;uint;struct*;struct*);" & _
		"DrawImage hresult(struct*;struct*;struct*;uint;uint);" & _
		"DrawGdiMetafile hresult(struct*;struct*);" & _
		"FillMesh hresult(struct*;struct*);" & _
		"FillOpacityMask hresult(struct*;struct*;struct*;struct*);" & _
		"FillGeometry hresult(struct*;struct*;struct*);" & _
		"FillRectangle hresult(struct*;struct*);" & _
		"PushAxisAlignedClip hresult(struct*;uint);" & _
		"PushLayer hresult(struct*;struct*);" & _
		"PopAxisAlignedClip hresult();" & _
		"PopLayer hresult();"

Global Const $tagID2D1CommandList = $tagID2D1Resource & _
		"Stream hresult(struct*);" & _
		"Close hresult();"

Global Const $tagID2D1PrintControl = "AddPage hresult(struct*;float;float;struct*;uint64*;uint64*);" & _
		"Close hresult();"

Global Const $tagID2D1ImageBrush = $tagID2D1Brush & _
		"SetImage none(struct*);" & _
		"SetExtendModeX none(uint);" & _
		"SetExtendModeY none(uint);" & _
		"SetInterpolationMode none(uint);" & _
		"SetSourceRectangle none(struct*);" & _
		"GetImage none(ptr*);" & _
		"GetExtendModeX uint();" & _
		"GetExtendModeY uint();" & _
		"GetInterpolationMode uint();" & _
		"GetSourceRectangle none(struct*);"

Global Const $tagID2D1BitmapBrush1 = $tagID2D1BitmapBrush & _
		"SetInterpolationMode1 none(uint);" & _
		"GetInterpolationMode1 uint();"

Global Const $tagID2D1StrokeStyle1 = $tagID2D1StrokeStyle & _
		"GetStrokeTransformType uint();"

Global Const $tagID2D1PathGeometry1 = $tagID2D1PathGeometry & _
		"ComputePointAndSegmentAtLength hresult(float;uint;struct*;float;struct*);"

Global Const $tagID2D1Properties = "GetPropertyCount uint();" & _
		"GetPropertyName hresult(uint;wstr;uint);" & _
		"GetPropertyNameLength uint(uint);" & _
		"GetType uint(uint);" & _
		"GetPropertyIndex uint(wstr);" & _
		"SetValueByName hresult(wstr;uint;struct*;uint);" & _
		"SetValue hresult(uint;uint;struct*;uint);" & _
		"GetValueByName hresult(wstr;uint;struct*;uint);" & _
		"GetValue hresult(uint;uint;struct*;uint);" & _
		"GetValueSize uint(uint);" & _
		"GetSubProperties hresult(uint;ptr*);"

Global Const $tagID2D1Effect = $tagID2D1Properties & _
		"SetInput none(uint;struct*;bool);" & _
		"SetInputCount hresult(uint);" & _
		"GetInput none(uint;ptr*);" & _
		"GetInputCount uint();" & _
		"GetOutput none(ptr*);"

Global Const $tagID2D1Bitmap1 = $tagID2D1Bitmap & _
		"GetColorContext none(ptr*);" & _
		"GetOptions uint();" & _
		"GetSurface hresult(ptr*);" & _
		"Map hresult(uint;struct*);" & _
		"Unmap hresult();"

Global Const $tagID2D1ColorContext = $tagID2D1Resource & _
		"GetColorSpace uint();" & _
		"GetProfileSize uint();" & _
		"GetProfile hresult(struct*;uint);"

Global Const $tagID2D1GradientStopCollection1 = $tagID2D1GradientStopCollection & _
		"GetGradientStops1 none(struct*;uint);" & _
		"GetPreInterpolationSpace uint();" & _
		"GetPostInterpolationSpace uint();" & _
		"GetBufferPrecision uint();" & _
		"GetColorInterpolationMode uint();"

Global Const $tagID2D1DrawingStateBlock1 = $tagID2D1DrawingStateBlock & _
		"GetDescription1 none(struct*);" & _
		"SetDescription1 none(struct*);"

Global Const $tagID2D1DeviceContext = __D2D_Inherit("CreateBitmap hresult(struct;struct*;uint;struct*;ptr*);" & _
		"CreateBitmapFromWicBitmap hresult(struct*;struct*;ptr*);" & _
		"CreateColorContext hresult(uint;struct*;uint;ptr*);" & _
		"CreateColorContextFromFilename hresult(wstr;ptr*);" & _
		"CreateColorContextFromWicColorContext hresult(struct*;ptr*);" & _
		"CreateBitmapFromDxgiSurface hresult(struct*;struct*;ptr*);" & _
		"CreateEffect hresult(struct*;ptr*);" & _
		"CreateGradientStopCollection hresult(struct*;uint;uint;uint;uint;uint;uint;ptr*);" & _
		"CreateImageBrush hresult(struct*;struct*;struct*;ptr*);" & _
		"CreateBitmapBrush hresult(struct*;struct*;struct*;ptr*);" & _
		"CreateCommandList hresult(ptr*);" & _
		"IsDxgiFormatSupported bool(uint);" & _
		"IsBufferPrecisionSupported bool(uint);" & _
		"GetImageLocalBounds hresult(struct*;struct*);" & _
		"GetImageWorldBounds hresult(struct*;struct*);" & _
		"GetGlyphRunWorldBounds hresult(float;float;struct*;uint;struct*);" & _
		"GetDevice none(ptr*);" & _
		"SetTarget none(struct*);" & _
		"GetTarget none(ptr*);" & _
		"SetRenderingControls none(struct*);" & _
		"GetRenderingControls none(struct*);" & _
		"SetPrimitiveBlend none(uint);" & _
		"GetPrimitiveBlend uint();" & _
		"SetUnitMode none(uint);" & _
		"GetUnitMode uint();" & _
		"DrawGlyphRun none(float;float;struct*;struct*;struct*;uint);" & _
		"DrawImage none(struct*;struct*;struct*;uint;uint);" & _
		"DrawGdiMetafile none(struct*;struct*);" & _
		"DrawBitmap none(struct*;struct*;float;uint;struct*;struct*);" & _
		"PushLayer none(struct*;struct*);" & _
		"InvalidateEffectInputRectangle hresult(struct*;uint;struct*);" & _
		"GetEffectInvalidRectangleCount hresult(struct*;uint*);" & _
		"GetEffectInvalidRectangles hresult(struct*;struct*;uint);" & _
		"GetEffectRequiredInputRectangles hresult(struct*;struct*;struct*;struct*;uint);" & _
		"FillOpacityMask none(struct*;struct*;struct*;struct*);", $tagID2D1RenderTarget, "1")

Global Const $tagID2D1Device = $tagID2D1Resource & _
		"CreateDeviceContext hresult(uint;ptr*);" & _
		"CreatePrintControl hresult(struct*;struct*;struct*;ptr*);" & _
		"SetMaximumTextureMemory none(uint64);" & _
		"GetMaximumTextureMemory ptr(struct*);" & _
		"ClearResources none(uint);"

Global Const $tagID2D1Factory1 = $tagID2D1Factory & _
		"CreateDevice hresult(struct*;ptr*);" & _
		"CreateStrokeStyle1 hresult(struct*;struct*;uint;ptr*);" & _
		"CreatePathGeometry1 hresult(ptr*);" & _
		"CreateDrawingStateBlock1 hresult(struct*;struct*;ptr*);" & _
		"CreateGdiMetafile hresult(struct*;ptr*);" & _
		"RegisterEffectFromStream hresult(struct*;struct*;struct*;uint;struct*);" & _
		"RegisterEffectFromString hresult(struct*;wstr;struct*;uint;struct*);" & _
		"UnregisterEffect hresult(struct*);" & _
		"GetRegisteredEffects hresult(struct*;uint;uint*;uint*);" & _
		"GetEffectProperties hresult(struct*;ptr*);"


Func __D2D_Inherit($sIntF_A, Const ByRef $sIntF_B, $sExt)
	Local $aIntF_B = StringRegExp($sIntF_B, "(\w+)\h+\w+\h*\(", 3)
	For $i = 0 To UBound($aIntF_B) - 1
		If StringRegExp($sIntF_A, "(?i)" & $aIntF_B[$i] & "\h+") Then $sIntF_A = StringRegExpReplace($sIntF_A, "(?i)(" & $aIntF_B[$i] & ")(\h+)", "${1}" & $sExt & "${2}")
	Next
	Return $sIntF_B & $sIntF_A
EndFunc   ;==>__D2D_Inherit